/**
 * lang.js — Shared translation utility for moensworld.com
 * Usage:
 *   window.t('key')           — get translation for current language
 *   window.setLang('en')      — switch language
 *   window.getLang()          — get current language ('no' | 'en')
 *   data-i18n="key"           — auto-translated on load + language switch
 *   data-i18n-placeholder="k" — translates input placeholder
 */
(function () {

  // ── Translations ────────────────────────────────────────────────────────────
  const T = {

    // ── Landing page ──────────────────────────────────────────────────────────
    no: {
      home_tagline:   'Personlige prosjekter innen sykling, seiling og teknologi',
      home_projects:  'Prosjekter',

      card_bikefit_title: 'BikeFit AI',
      card_bikefit_desc:  'Finn din perfekte sykkelposisjon med AI-basert posisjonsanalyse direkte i nettleseren. Last opp bilde eller bruk kamera.',
      card_weather_title: 'Norsk Vær Live',
      card_weather_desc:  'Live værkart for hele Norge med data fra Meteorologisk institutt. Vind, temperatur, nedbør og lynnedslag i animert kart.',
      card_sail_title:    'Seilinstrument',
      card_sail_desc:     'Seilinstrument med mulighet for VMG-beregninger gjennom koordinater.',
      card_moensail_title:'Sammenligning av seilbåter',
      card_moensail_desc: 'Sammenligner seilbåter med gyldige Norrating målebrev. Visualiser forskjellene i tabeller og beregn seiltid gjennom waypoints med ulik vind.',
      card_kyst_title:    'Kystværet',
      card_kyst_desc:     'Vindoversikt fra Kystverkets database med visualisering.',
      card_klesty_title:  'Klesstørrelse',
      card_klesty_desc:   'Estimer kroppsmål og klesstørrelser fra bilde. Oppgi høyde som referanse, last opp et frontbilde og få størrelsesanbefalinger.',

      // ── BikeFit ─────────────────────────────────────────────────────────────
      bf_sub:            'Finn din perfekte sykkelposisjon',
      bf_s1:             'Modus', bf_s2: 'Sykkeltype', bf_s3: 'Kjørestil',
      bf_s4:             'Mål',   bf_s5: 'Resultat',
      bf_mode_title:     '🎯 Velg modus',
      bf_mode_simple:    'Enkel',
      bf_mode_simple_d:  'Kun høyde — raskt og enkelt',
      bf_mode_adv:       'Avansert',
      bf_mode_adv_d:     'Alle kroppsmål — presis tilpasning',
      bf_bike_title:     '🚲 Sykkeltype',
      bf_bt_road:        'Landevei',   bf_bt_road_d:   'Rask, aero',
      bf_bt_gravel:      'Gravel',     bf_bt_gravel_d: 'Allround',
      bf_bt_mtb:         'MTB',        bf_bt_mtb_d:    'Terreng',
      bf_bt_city:        'By/Hybrid',  bf_bt_city_d:   'Daglig',
      bf_bt_tt:          'TT/Tri',     bf_bt_tt_d:     'Maks aero',
      bf_style_title:    '🎚️ Kjørestil og posisjon',
      bf_pos0:           '🏁 Aggressiv', bf_pos0s: 'Race',
      bf_pos1:           '⚡ Sport',     bf_pos1s: 'Balansert',
      bf_pos2:           '🌿 Komfort',   bf_pos2s: 'Avslappet',
      bf_pos3:           '🛋️ Oppreist', bf_pos3s: 'Touring',
      bf_pos0_long: 'Race/Aero — Lav og lang, maksimal effektivitet',
      bf_pos1_long: 'Balansert mellom ytelse og komfort',
      bf_pos2_long: 'Avslappet posisjon — passer lengre turer',
      bf_pos3_long: 'Touring/by — maksimal komfort og sikt',
      bf_photo_title:    '📸 Mål kropp fra bilde',
      bf_photo_intro:    'Last opp et bilde av deg selv, oppgi høyde, og AI-en beregner inseam, overkropp, armlengde og skulderbredde automatisk. Verdiene fylles direkte inn i skjemaet under.',
      bf_tip1: '🧍 Hel kropp synlig', bf_tip2: '👀 Forsiden mot kamera',
      bf_tip3: '💡 Godt lys, jevn bakgrunn', bf_tip4: '👐 Armer langs siden',
      bf_tip5: '👟 Stå rett og oppreist',
      bf_your_height:    'Din høyde',
      bf_upload_btn:     '📷 Last opp bilde',
      bf_use_meas:       '✅ Bruk disse målene — fyll inn skjema automatisk',
      bf_photo_note:     '⚠️ AI-estimater — sjekk og juster gjerne verdiene manuelt i skjemaet under.',
      bf_meas_title:     '📏 Kroppsmål',
      bf_height:         'Høyde',
      bf_height_hint:    'Total kroppshøyde uten sko',
      bf_inseam:         'Skritthøyde',
      bf_inseam_hint:    'Fra gulv til lyske (med bok)',
      bf_armspan:        'Armspenn',
      bf_armspan_hint:   'Fingertipp til fingertipp',
      bf_torso:          'Overkropp',
      bf_torso_hint:     'Fra lyske til skulder',
      bf_armlen:         'Armlengde',
      bf_armlen_hint:    'Fra skulder til håndledd',
      bf_shoulder:       'Skulderbredde',
      bf_shoulder_hint:  'Skulder til skulder (ben)',
      bf_calc_btn:       '📐 Beregn min sykkelfit',
      bf_viz_title:      '🚴 Din sykkelposisjon',
      bf_res_title:      '📊 Anbefalte mål',
      bf_recs_title:     '💡 Anbefalinger',
      bf_modal_close:    'Lukk',
      bf_conf_high:      '🟢 Høy sikkerhet', bf_conf_med: '🟡 Middels sikkerhet', bf_conf_low: '🔴 Lav sikkerhet',
      // Result labels
      bf_lbl_saddle:     'Sadelhøyde (BB→sadel)', bf_lbl_crank: 'Krankarmlengde',
      bf_lbl_hbw:        'Styrebredde',           bf_lbl_reach: 'Reach',
      bf_lbl_stack:      'Stack',                 bf_lbl_drop:  'Styre vs. sadel',
      bf_lbl_setback:    'Sadelsetback',           bf_lbl_stem:  'Styrestamme',
      bf_lbl_frame:      'Rammestørrelse (estimat)',
      // Detected
      bf_det_inseam:     'Skritthøyde', bf_det_torso: 'Overkropp',
      bf_det_shoulder:   'Skulderbredde', bf_det_arm: 'Armlengde', bf_det_armspan: 'Armspenn',
      // Guides
      bf_guide_height_title: 'Mål høyde', bf_guide_height_sub: 'Uten sko, stående rett',
      bf_guide_height_text: 'Stå rett mot en vegg uten sko. Legg en bok flatt på toppen av hodet og merk av på veggen. Mål fra gulv til merket.',
      bf_guide_inseam_title: 'Mål skritthøyde', bf_guide_inseam_sub: 'Inseam — fra gulv til lyske',
      bf_guide_inseam_text: 'Stå uten sko mot en vegg. Trykk en bok hardt opp i skrittet (som en sykkelsadel). Mål fra gulv til overkant av boken. Ta 2–3 målinger og bruk gjennomsnittet.',
      bf_guide_armspan_title: 'Mål armspenn', bf_guide_armspan_sub: 'Vingespenn — fingertipp til fingertipp',
      bf_guide_armspan_text: 'Stå med ryggen mot en vegg, strekk armene rett ut til siden. Mål fra fingertipp til fingertipp. Armspenn er normalt lik høyden ±5 cm.',
      bf_guide_torso_title: 'Mål overkropp', bf_guide_torso_sub: 'Fra lyske til skulder',
      bf_guide_torso_text: 'Sitt på en stol med rett rygg. Mål fra sittebenet (lyske) til toppen av skulderen (acromion). Lengre overkropp → lengre styrestamme.',
      bf_guide_arm_title: 'Mål armlengde', bf_guide_arm_sub: 'Fra skulder til håndledd',
      bf_guide_arm_text: 'La armen henge naturlig, mål fra skulderleddet (acromion) til håndleddet (utsiden). Hold en liten bøy i albuen.',
      bf_guide_shoulder_title: 'Mål skulderbredde', bf_guide_shoulder_sub: 'Ben skulderbredde',
      bf_guide_shoulder_text: 'Mål fra det benpunktet på venstre skulder (acromion) til tilsvarende punkt på høyre skulder. Ikke mykdelbredden — bruk fingrene til å finne benkanten.',
      // Recommendations
      bf_rec_saddle_h:   'Sadelhøyde: {v} mm',
      bf_rec_saddle_p:   'Mål fra midten av tråkkakselen (BB) til toppen av setet. Kneet skal ha 145–155° bøy ved bunnen av pedalsyklusen. Juster i 3 mm-skritt og gi kroppen noen turer mellom hver endring.',
      bf_rec_setback_h:  'Sadelsetback: {v} mm bak BB',
      bf_rec_setback_p:  'Med pedalene vannrett skal midten av kneet peke rett ned over pedalaksen (KOPS-metoden). Bruk en loddsnor fra kneleddet for å sjekke. Sadelskinner gir typisk 20–30 mm justeringsrom.',
      bf_rec_crank_h:    'Krankarmlengde: {v} mm',
      bf_rec_crank_p_road: 'Basert på skritthøyden din. Kortere krankarmer gir jevnere pedalslag og reduserer hoftebelastning — spesielt gunstig for landeveiskjøring og høy kadens.',
      bf_rec_crank_p_mtb:  'Basert på skritthøyden din. Kortere krankarmer gir jevnere pedalslag og reduserer hoftebelastning — spesielt gunstig for MTB og terrengkjøring.',
      bf_rec_hbw_h:      'Styrebredde: {v} mm',
      bf_rec_hbw_p_road: 'For drop-styre: match skulderbredden (biacromial). Smalere gir bedre aerodynamikk, bredere øker stabiliteten.',
      bf_rec_hbw_p_mtb:  'Bredere styre gir bedre kontroll i terreng. Klipp til ønsket bredde — start bredt og kutt til du finner komfortzonen.',
      bf_rec_hbw_p_other:'Match skulderbredden pluss ~10 cm for god komfort og kontroll.',
      bf_rec_stack_h:    'Stack/Reach: {stack}/{reach} mm',
      bf_rec_stack_p:    'Disse er rammegeometrimålene. Sammenlign med produsentenes geometritabeller for å finne riktig ramme. Styrestammelengde (≈{stem} mm) og høyde på stigerøret finjusterer posisjonen.',
      bf_rec_drop_h_pos: 'Styret er {v} mm under sadelen',
      bf_rec_drop_h_neg: 'Styret er {v} mm over sadelen',
      bf_rec_drop_p_pos: '{pos}-posisjon gir dette droppet. Bruk spacers under styrestammen for å heve styret, eller juster stammevinkel.',
      bf_rec_drop_p_neg: 'Styret er høyere enn sadelen — typisk for komfort- og byposisjon.',
      bf_rec_adjust_h:   'Test og juster gradvis',
      bf_rec_adjust_p:   'Disse verdiene er et solid utgangspunkt. Gjør én endring av gangen — vent 2–3 turer før neste. Vedvarende smerter i kne, rygg eller nakke? Oppsøk en profesjonell bikefitter.',
      bf_bar_under:      '{v} mm under sadelen',
      bf_bar_over:       '{v} mm over sadelen',

      // ── Klesstørrelse ────────────────────────────────────────────────────────
      ks_subtitle:      'Estimer kroppsmål og klesstørrelser fra to bilder',
      ks_prog1:         'Steg 1 av 3', ks_prog2: 'Steg 2 av 3', ks_prog3: 'Steg 3 av 3', ks_done: 'Ferdig',
      ks_height_title:  '📏 Oppgi din høyde',
      ks_height_hint:   'Brukes som absolutt referanse for å beregne alle mål i centimeter.',
      ks_height_info:   '💡 Med to bilder beregnes omkretsene fra faktisk bredde og dybde ved hjelp av ellipseformelen — mye mer presist enn enkeltbilde.',
      ks_continue:      'Fortsett →',
      ks_photo_title:   '📸 Last opp to bilder',
      ks_photo_hint:    'Et forfra og et fra siden — stå rett, hel kropp synlig, armene litt ut.',
      ks_front_lbl:     'Forfra',
      ks_side_lbl:      'Fra siden',
      ks_selected:      '✓ Valgt',
      ks_click_drop:    'Klikk eller slipp',
      ks_front_sub:     'Stå rett mot kamera, full kropp',
      ks_side_sub:      'Stå 90° til kamera, full kropp',
      ks_tip_straight:  'Forfra, rett opp og ned',
      ks_tip_arms:      'Armene ~15 cm ut fra kroppen',
      ks_tip_full:      'Hode til føtter synlig',
      ks_tip_clothes:   'Tett- eller trettsittende klær',
      ks_side_tip1:     'Profil mot kamera (90°)',
      ks_side_tip2:     'Armene langs siden',
      ks_side_tip3:     'Hode til føtter synlig',
      ks_side_tip4:     'Ensfarget bakgrunn anbefales',
      ks_back:          '← Endre høyde',
      ks_analyze:       'Analyser →',
      ks_loading:       'Laster AI-modell...',
      ks_res_title:     '🎯 Analyse av bilder',
      ks_from_front:    'Forfra — breddemål',
      ks_from_side:     'Fra siden — dybdemål',
      ks_legend_front:  'Fremre bilde (bredde)',
      ks_legend_side:   'Sidebilde (dybde)',
      ks_legend_comb:   'Kombinert (omkrets)',
      ks_linear_sec:    'Lengde og bredde (forfra)',
      ks_depth_sec:     'Dybdemål (fra siden)',
      ks_circ_sec:      'Beregnet omkrets',
      ks_lbl_shoulder:  'Skulder',  ks_lbl_hip:    'Hofte',
      ks_lbl_torso:     'Torso',    ks_lbl_arm:    'Arm',
      ks_lbl_leg:       'Bein',     ks_lbl_inseam: 'Innsøm',
      ks_lbl_chest_d:   'Brystdybde', ks_lbl_waist_d: 'Midjedybde', ks_lbl_hip_d: 'Hoftedybde',
      ks_lbl_chest_c:   'Brystomkrets', ks_lbl_waist_c: 'Midjeomkrets', ks_lbl_hip_c: 'Hofteomkrets',
      ks_src_front:     'forfra',  ks_src_silh: 'siluett', ks_src_est: 'estimat', ks_src_ellipse: 'ellipse bredde+dybde',
      ks_sizes_title:   '👕 Anbefalte størrelser',
      ks_sizes_hint:    'Beregnet fra kombinerte bredde- og dybdemål.',
      ks_cat_top:       'T-skjorte / Genser',
      ks_cat_jacket:    'Jakke / Dress (EU)',
      ks_cat_pants_i:   'Bukse (internasjonal)',
      ks_cat_pants_eu:  'Bukse (EU)',
      ks_cat_shoulder:  'Skulderbredde',
      ks_cat_arm:       'Armlengde',
      ks_acc_high:      '★ God nøyaktighet',  ks_acc_med: '~ Estimat',
      ks_arm_short:     'Kort', ks_arm_normal: 'Normal', ks_arm_long: 'Lang',
      ks_warning:       '⚠️ Estimatene er beregnet fra 2D-bilder med brukerens høyde som eneste absolutte referanse. Sidebilde-dybden krever jevn bakgrunn for best nøyaktighet. Bekreft alltid med målebånd ved kjøp.',
      ks_new_images:    '← Nye bilder',
      ks_new_height:    '← Ny høyde',
      ks_detail_chest:  'Bryst ~{v} cm',
      ks_detail_jacket: 'EU · bryst ~{v} cm',
      ks_detail_pants_i:'Midje ~{w} cm · innsøm ~{i} cm',
      ks_detail_pants_eu:'EU · midje ~{v} cm',
      ks_detail_shoulder:'Relevant for jakker og skjorter',
      ks_detail_arm:    '~{v} cm (skulder → håndledd)',
      ks_wp_placeholder: 'Navn (f.eks. Merke 1)',

      // ── Sailing ──────────────────────────────────────────────────────────────
      sail_gps_wait:    'Venter på GPS…',
      sail_compass_txt: '📱 Aktiver kompass for heading',
      sail_compass_btn: 'Aktiver',
      sail_no_wp:       '🏳 Ingen aktiv waypoint',
      sail_vmg_sub:     'mot mål',
      sail_brg_sub:     'bearing til mål',
      sail_dtw_sub:     'avstand',
      sail_hdg_sub:     'kompass',
      sail_sog_sub:     'knop',
      sail_cog_sub:     'grader',
      sail_map_hint:    'Hold inne på kartet for å legge til waypoint',
      sail_wp_title:    'Waypoints',
      sail_wp_empty:    'Ingen waypoints ennå.<br>Hold inne på kartet for å legge til.',
      sail_modal_title: 'Nytt waypoint',
      sail_cancel:      'Avbryt',
      sail_add:         'Legg til',
      sail_tab_dash:    'Instrumenter',
      sail_tab_map:     'Kart',
      sail_tab_wp:      'Waypoints',
      sail_wp_active:   '★ Aktiv',
      sail_wp_select:   'Velg',
      sail_wp_delete:   'Slett',
      sail_wp_name_ph:    'Navn (f.eks. Merke 1)',
      sail_wp_deactivate: 'Deaktiver',
      sail_wp_set_target: 'Velg som mål',
    },

    en: {
      home_tagline:   'Personal projects in cycling, sailing and technology',
      home_projects:  'Projects',

      card_bikefit_title: 'BikeFit AI',
      card_bikefit_desc:  'Find your perfect bike position with AI-based position analysis directly in the browser. Upload a photo or use your camera.',
      card_weather_title: 'Norwegian Weather Live',
      card_weather_desc:  'Live weather map for all of Norway with data from the Meteorological Institute. Wind, temperature, precipitation and lightning in an animated map.',
      card_sail_title:    'Sailing Instrument',
      card_sail_desc:     'Sailing instrument with VMG calculations through coordinates.',
      card_moensail_title:'Sailboat Comparison',
      card_moensail_desc: 'Compare sailboats with valid Norrating rating certificates. Visualise differences in tables and calculate sailing time through waypoints with varying wind.',
      card_kyst_title:    'Coastal Weather',
      card_kyst_desc:     'Wind overview from the Norwegian Coastal Administration database with visualisation.',
      card_klesty_title:  'Clothing Size',
      card_klesty_desc:   'Estimate body measurements and clothing sizes from photos. Provide your height as a reference, upload a front photo and get size recommendations.',

      bf_sub:            'Find your perfect bike position',
      bf_s1:             'Mode', bf_s2: 'Bike type', bf_s3: 'Riding style',
      bf_s4:             'Measurements', bf_s5: 'Result',
      bf_mode_title:     '🎯 Choose mode',
      bf_mode_simple:    'Simple',
      bf_mode_simple_d:  'Height only — quick and easy',
      bf_mode_adv:       'Advanced',
      bf_mode_adv_d:     'All body measurements — precise fitting',
      bf_bike_title:     '🚲 Bike type',
      bf_bt_road:        'Road',       bf_bt_road_d:   'Fast, aero',
      bf_bt_gravel:      'Gravel',     bf_bt_gravel_d: 'All-round',
      bf_bt_mtb:         'MTB',        bf_bt_mtb_d:    'Off-road',
      bf_bt_city:        'City/Hybrid',bf_bt_city_d:   'Daily use',
      bf_bt_tt:          'TT/Tri',     bf_bt_tt_d:     'Max aero',
      bf_style_title:    '🎚️ Riding style and position',
      bf_pos0:           '🏁 Aggressive', bf_pos0s: 'Race',
      bf_pos1:           '⚡ Sport',       bf_pos1s: 'Balanced',
      bf_pos2:           '🌿 Comfort',     bf_pos2s: 'Relaxed',
      bf_pos3:           '🛋️ Upright',    bf_pos3s: 'Touring',
      bf_pos0_long: 'Race/Aero — Low and long, maximum efficiency',
      bf_pos1_long: 'Balanced between performance and comfort',
      bf_pos2_long: 'Relaxed position — suited for longer rides',
      bf_pos3_long: 'Touring/city — maximum comfort and visibility',
      bf_photo_title:    '📸 Measure body from photo',
      bf_photo_intro:    'Upload a photo of yourself, enter your height, and the AI calculates inseam, torso, arm length and shoulder width automatically. The values are filled directly into the form below.',
      bf_tip1: '🧍 Full body visible', bf_tip2: '👀 Front facing camera',
      bf_tip3: '💡 Good light, plain background', bf_tip4: '👐 Arms at sides',
      bf_tip5: '👟 Stand straight and upright',
      bf_your_height:    'Your height',
      bf_upload_btn:     '📷 Upload photo',
      bf_use_meas:       '✅ Use these measurements — fill form automatically',
      bf_photo_note:     '⚠️ AI estimates — please check and adjust values manually in the form below.',
      bf_meas_title:     '📏 Body measurements',
      bf_height:         'Height',
      bf_height_hint:    'Total body height without shoes',
      bf_inseam:         'Inseam',
      bf_inseam_hint:    'Floor to crotch (using a book)',
      bf_armspan:        'Arm span',
      bf_armspan_hint:   'Fingertip to fingertip',
      bf_torso:          'Torso',
      bf_torso_hint:     'From crotch to shoulder',
      bf_armlen:         'Arm length',
      bf_armlen_hint:    'From shoulder to wrist',
      bf_shoulder:       'Shoulder width',
      bf_shoulder_hint:  'Shoulder to shoulder (bone)',
      bf_calc_btn:       '📐 Calculate my bike fit',
      bf_viz_title:      '🚴 Your bike position',
      bf_res_title:      '📊 Recommended measurements',
      bf_recs_title:     '💡 Recommendations',
      bf_modal_close:    'Close',
      bf_conf_high:      '🟢 High confidence', bf_conf_med: '🟡 Medium confidence', bf_conf_low: '🔴 Low confidence',
      bf_lbl_saddle:     'Saddle height (BB→saddle)', bf_lbl_crank: 'Crank arm length',
      bf_lbl_hbw:        'Handlebar width',           bf_lbl_reach: 'Reach',
      bf_lbl_stack:      'Stack',                     bf_lbl_drop:  'Bar vs. saddle',
      bf_lbl_setback:    'Saddle setback',             bf_lbl_stem:  'Stem length',
      bf_lbl_frame:      'Frame size (estimate)',
      bf_det_inseam:     'Inseam', bf_det_torso: 'Torso',
      bf_det_shoulder:   'Shoulder width', bf_det_arm: 'Arm length', bf_det_armspan: 'Arm span',
      bf_guide_height_title: 'Measure height', bf_guide_height_sub: 'Without shoes, standing straight',
      bf_guide_height_text: 'Stand straight against a wall without shoes. Place a book flat on top of your head and mark the wall. Measure from floor to the mark.',
      bf_guide_inseam_title: 'Measure inseam', bf_guide_inseam_sub: 'Inseam — floor to crotch',
      bf_guide_inseam_text: 'Stand without shoes against a wall. Press a book firmly up into your crotch (like a bike saddle). Measure from floor to top of book. Take 2–3 measurements and use the average.',
      bf_guide_armspan_title: 'Measure arm span', bf_guide_armspan_sub: 'Wingspan — fingertip to fingertip',
      bf_guide_armspan_text: 'Stand with your back against a wall, stretch arms straight out to the sides. Measure fingertip to fingertip. Arm span is normally equal to height ±5 cm.',
      bf_guide_torso_title: 'Measure torso', bf_guide_torso_sub: 'From crotch to shoulder',
      bf_guide_torso_text: 'Sit on a chair with straight back. Measure from the sitting bone (crotch) to the top of the shoulder (acromion). Longer torso → longer stem.',
      bf_guide_arm_title: 'Measure arm length', bf_guide_arm_sub: 'From shoulder to wrist',
      bf_guide_arm_text: 'Let the arm hang naturally, measure from the shoulder joint (acromion) to the wrist (outside). Keep a slight bend in the elbow.',
      bf_guide_shoulder_title: 'Measure shoulder width', bf_guide_shoulder_sub: 'Bony shoulder width',
      bf_guide_shoulder_text: 'Measure from the bony point on the left shoulder (acromion) to the corresponding point on the right shoulder. Not the soft tissue width — use your fingers to find the bone edge.',
      bf_rec_saddle_h:   'Saddle height: {v} mm',
      bf_rec_saddle_p:   'Measure from the centre of the bottom bracket (BB) to the top of the saddle. Knee should have 145–155° bend at the bottom of the pedal stroke. Adjust in 3 mm increments and allow a few rides between changes.',
      bf_rec_setback_h:  'Saddle setback: {v} mm behind BB',
      bf_rec_setback_p:  'With pedals horizontal, the centre of the knee should point straight down over the pedal axle (KOPS method). Use a plumb line from the knee joint to check. Seat rails typically allow 20–30 mm of adjustment.',
      bf_rec_crank_h:    'Crank arm length: {v} mm',
      bf_rec_crank_p_road: 'Based on your inseam. Shorter cranks give a smoother pedal stroke and reduce hip stress — especially beneficial for road riding and high cadence.',
      bf_rec_crank_p_mtb:  'Based on your inseam. Shorter cranks give a smoother pedal stroke and reduce hip stress — especially beneficial for MTB and off-road riding.',
      bf_rec_hbw_h:      'Handlebar width: {v} mm',
      bf_rec_hbw_p_road: 'For drop bars: match shoulder width (biacromial). Narrower gives better aerodynamics, wider increases stability.',
      bf_rec_hbw_p_mtb:  'Wider bars give better control off-road. Cut to desired width — start wide and cut until you find your comfort zone.',
      bf_rec_hbw_p_other:'Match shoulder width plus ~10 cm for good comfort and control.',
      bf_rec_stack_h:    'Stack/Reach: {stack}/{reach} mm',
      bf_rec_stack_p:    'These are frame geometry measurements. Compare with manufacturer geometry charts to find the right frame. Stem length (≈{stem} mm) and spacer height fine-tune the position.',
      bf_rec_drop_h_pos: 'Bar is {v} mm below saddle',
      bf_rec_drop_h_neg: 'Bar is {v} mm above saddle',
      bf_rec_drop_p_pos: '{pos} position gives this drop. Use spacers under the stem to raise the bar, or adjust stem angle.',
      bf_rec_drop_p_neg: 'Bar is higher than saddle — typical for comfort and city position.',
      bf_rec_adjust_h:   'Test and adjust gradually',
      bf_rec_adjust_p:   'These values are a solid starting point. Make one change at a time — wait 2–3 rides before the next. Persistent pain in knees, back or neck? Consult a professional bike fitter.',
      bf_bar_under:      '{v} mm below saddle',
      bf_bar_over:       '{v} mm above saddle',

      ks_subtitle:      'Estimate body measurements and clothing sizes from two photos',
      ks_prog1:         'Step 1 of 3', ks_prog2: 'Step 2 of 3', ks_prog3: 'Step 3 of 3', ks_done: 'Done',
      ks_height_title:  '📏 Enter your height',
      ks_height_hint:   'Used as absolute reference to calculate all measurements in centimetres.',
      ks_height_info:   '💡 With two photos, circumferences are calculated from actual width and depth using the ellipse formula — much more accurate than a single photo.',
      ks_continue:      'Continue →',
      ks_photo_title:   '📸 Upload two photos',
      ks_photo_hint:    'One from the front and one from the side — stand straight, full body visible, arms slightly out.',
      ks_front_lbl:     'Front',
      ks_side_lbl:      'Side',
      ks_selected:      '✓ Selected',
      ks_click_drop:    'Click or drop',
      ks_front_sub:     'Stand straight facing camera, full body',
      ks_side_sub:      'Stand 90° to camera, full body',
      ks_tip_straight:  'Front facing, standing straight',
      ks_tip_arms:      'Arms ~15 cm out from body',
      ks_tip_full:      'Head to feet visible',
      ks_tip_clothes:   'Tight or form-fitting clothes',
      ks_side_tip1:     'Profile to camera (90°)',
      ks_side_tip2:     'Arms along the sides',
      ks_side_tip3:     'Head to feet visible',
      ks_side_tip4:     'Plain background recommended',
      ks_back:          '← Change height',
      ks_analyze:       'Analyse →',
      ks_loading:       'Loading AI model...',
      ks_res_title:     '🎯 Photo analysis',
      ks_from_front:    'Front — width measurements',
      ks_from_side:     'Side — depth measurements',
      ks_legend_front:  'Front photo (width)',
      ks_legend_side:   'Side photo (depth)',
      ks_legend_comb:   'Combined (circumference)',
      ks_linear_sec:    'Length and width (front)',
      ks_depth_sec:     'Depth measurements (side)',
      ks_circ_sec:      'Calculated circumference',
      ks_lbl_shoulder:  'Shoulder', ks_lbl_hip:    'Hip',
      ks_lbl_torso:     'Torso',    ks_lbl_arm:    'Arm',
      ks_lbl_leg:       'Leg',      ks_lbl_inseam: 'Inseam',
      ks_lbl_chest_d:   'Chest depth', ks_lbl_waist_d: 'Waist depth', ks_lbl_hip_d: 'Hip depth',
      ks_lbl_chest_c:   'Chest circumference', ks_lbl_waist_c: 'Waist circumference', ks_lbl_hip_c: 'Hip circumference',
      ks_src_front:     'front', ks_src_silh: 'silhouette', ks_src_est: 'estimate', ks_src_ellipse: 'ellipse width+depth',
      ks_sizes_title:   '👕 Recommended sizes',
      ks_sizes_hint:    'Calculated from combined width and depth measurements.',
      ks_cat_top:       'T-shirt / Jumper',
      ks_cat_jacket:    'Jacket / Suit (EU)',
      ks_cat_pants_i:   'Trousers (international)',
      ks_cat_pants_eu:  'Trousers (EU)',
      ks_cat_shoulder:  'Shoulder width',
      ks_cat_arm:       'Arm length',
      ks_acc_high:      '★ Good accuracy', ks_acc_med: '~ Estimate',
      ks_arm_short:     'Short', ks_arm_normal: 'Normal', ks_arm_long: 'Long',
      ks_warning:       "⚠️ Estimates are calculated from 2D photos with the user's height as the only absolute reference. Side photo depth requires a plain background for best accuracy. Always confirm with a tape measure before purchasing.",
      ks_new_images:    '← New photos',
      ks_new_height:    '← New height',
      ks_detail_chest:  'Chest ~{v} cm',
      ks_detail_jacket: 'EU · chest ~{v} cm',
      ks_detail_pants_i:'Waist ~{w} cm · inseam ~{i} cm',
      ks_detail_pants_eu:'EU · waist ~{v} cm',
      ks_detail_shoulder:'Relevant for jackets and shirts',
      ks_detail_arm:    '~{v} cm (shoulder → wrist)',
      ks_wp_placeholder: 'Name (e.g. Mark 1)',

      sail_gps_wait:    'Waiting for GPS…',
      sail_compass_txt: '📱 Enable compass for heading',
      sail_compass_btn: 'Enable',
      sail_no_wp:       '🏳 No active waypoint',
      sail_vmg_sub:     'to target',
      sail_brg_sub:     'bearing to target',
      sail_dtw_sub:     'distance',
      sail_hdg_sub:     'compass',
      sail_sog_sub:     'knots',
      sail_cog_sub:     'degrees',
      sail_map_hint:    'Long press on map to add waypoint',
      sail_wp_title:    'Waypoints',
      sail_wp_empty:    'No waypoints yet.<br>Long press on the map to add.',
      sail_modal_title: 'New waypoint',
      sail_cancel:      'Cancel',
      sail_add:         'Add',
      sail_tab_dash:    'Instruments',
      sail_tab_map:     'Map',
      sail_tab_wp:      'Waypoints',
      sail_wp_active:   '★ Active',
      sail_wp_select:   'Select',
      sail_wp_delete:   'Delete',
      sail_wp_name_ph:    'Name (e.g. Mark 1)',
      sail_wp_deactivate: 'Deactivate',
      sail_wp_set_target: 'Set as target',
    }
  };

  // ── Core API ─────────────────────────────────────────────────────────────────
  window.getLang = () => localStorage.getItem('lang') || 'no';

  window.t = (key) => {
    const l = window.getLang();
    return (T[l] && T[l][key]) || (T.no && T.no[key]) || key;
  };

  window.setLang = (lang) => {
    localStorage.setItem('lang', lang);
    document.documentElement.lang = lang;
    window.applyTranslations();
    if (typeof window.onLangChange === 'function') window.onLangChange(lang);
  };

  window.applyTranslations = () => {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      const val = window.t(key);
      if (el.dataset.i18nHtml !== undefined) el.innerHTML = val;
      else el.textContent = val;
    });
    document.querySelectorAll('[data-i18n-ph]').forEach(el => {
      el.placeholder = window.t(el.dataset.i18nPh);
    });
    document.querySelectorAll('[data-lang-btn]').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.langBtn === window.getLang());
    });
  };

  // ── Shared CSS injected once ──────────────────────────────────────────────────
  const css = `
    .lang-sw{display:flex;gap:4px;align-items:center;}
    .lang-sw button{
      background:transparent;border:1px solid rgba(255,255,255,0.25);
      border-radius:6px;color:rgba(255,255,255,0.65);cursor:pointer;
      font-size:11px;font-weight:700;padding:4px 9px;transition:all .18s;
      line-height:1;
    }
    .lang-sw button.active{background:rgba(255,255,255,0.18);color:#fff;border-color:rgba(255,255,255,0.55);}
    .lang-sw button:hover{background:rgba(255,255,255,0.12);}
    /* bikefit uses light header — override */
    .lang-sw.dark button{border-color:rgba(0,0,0,0.2);color:rgba(0,0,0,0.5);}
    .lang-sw.dark button.active{background:rgba(0,0,0,0.12);color:#222;border-color:rgba(0,0,0,0.4);}
  `;
  const s = document.createElement('style');
  s.textContent = css;
  document.head.appendChild(s);

  // ── Auto-apply on DOMContentLoaded ────────────────────────────────────────────
  document.addEventListener('DOMContentLoaded', () => {
    document.documentElement.lang = window.getLang();
    window.applyTranslations();
  });

})();
